// <auto-generated />
using System;
using CannedNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CannedNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331191343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CannedNet.Account", b =>
                {
                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "displayName");

                    b.Property<int?>("IdentityFlags")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "identityFlags");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isJunior");

                    b.Property<int?>("PersonalPronouns")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "personalPronouns");

                    b.Property<int?>("Platforms")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profileImage");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CannedNet.CachedLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("PlatformID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("RequirePassword")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformID")
                        .IsUnique();

                    b.ToTable("cached_logins", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
