// <auto-generated />
using System;
using System.Collections.Generic;
using CannedNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CannedNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405025724_AddFriendlyNameToEarnableRewards")]
    partial class AddFriendlyNameToEarnableRewards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CannedNet.Account", b =>
                {
                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "displayName");

                    b.Property<int?>("IdentityFlags")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "identityFlags");

                    b.Property<bool>("IsJunior")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isJunior");

                    b.Property<int?>("PersonalPronouns")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "personalPronouns");

                    b.Property<int?>("Platforms")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platforms");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profileImage");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CannedNet.AvatarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemType");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "friendlyName");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("PlatformMask")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platformMask");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rarity");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tooltip");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("avatar_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.CachedLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "lastLoginTime");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<string>("PlatformID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "platformId");

                    b.Property<bool>("RequirePassword")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "requirePassword");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "PlatformID");

                    b.ToTable("cached_logins", (string)null);
                });

            modelBuilder.Entity("CannedNet.LoadScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isThumbnail");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tooltip");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("load_screens", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveDurationMinutes")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "ActiveDurationMinutes");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "ConsumableItemDesc");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Count");

                    b.Property<List<DateTime>>("CreatedAts")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasAnnotation("Relational:JsonPropertyName", "CreatedAts");

                    b.Property<List<int>>("Ids")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasAnnotation("Relational:JsonPropertyName", "Ids");

                    b.Property<int>("InitialCount")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "InitialCount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "IsActive");

                    b.Property<bool>("IsTransferable")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "IsTransferable");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("consumable_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.EarnableReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemType");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "consumableItemDesc");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GiftRarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "giftRarity");

                    b.Property<int>("RewardContext")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "rewardContext");

                    b.HasKey("Id");

                    b.HasIndex("RewardContext");

                    b.ToTable("earnable_rewards", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.GiftDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .HasColumnType("text");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer");

                    b.Property<string>("ConsumableItemDesc")
                        .HasColumnType("text");

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentModificationGuid")
                        .HasColumnType("text");

                    b.Property<string>("EquipmentPrefabName")
                        .HasColumnType("text");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GiftDropId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsQuery")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemSetFriendlyName")
                        .HasColumnType("text");

                    b.Property<int?>("ItemSetId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("SubscribersOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Tooltip")
                        .HasColumnType("text");

                    b.Property<bool>("Unique")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontItemId");

                    b.ToTable("gift_drops", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.ReceivedGift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemType");

                    b.Property<int>("BalanceType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "balanceType");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "consumableItemDesc");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "consumedAt");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "currency");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "currencyType");

                    b.Property<string>("EquipmentModificationGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "equipmentModificationGuid");

                    b.Property<string>("EquipmentPrefabName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "equipmentPrefabName");

                    b.Property<int?>("FromPlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "fromPlayerId");

                    b.Property<int>("GiftContext")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "giftContext");

                    b.Property<int>("GiftRarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "giftRarity");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isConsumed");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<int>("PlatformsToSpawnOn")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platformsToSpawnOn");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "receivedAt");

                    b.Property<int>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "receiverAccountId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "xp");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("ReceiverAccountId", "IsConsumed");

                    b.ToTable("received_gifts", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.Storefront", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StorefrontType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("storefronts", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NewUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PurchasableItemId")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontId");

                    b.ToTable("storefront_items", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("StorefrontItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StorefrontItemId");

                    b.ToTable("storefront_prices", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "SkinColor");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("player_avatars", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerBio", b =>
                {
                    b.Property<int>("accountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("accountId"));

                    b.HasKey("accountId");

                    b.ToTable("player_bios", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerProgression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "xp");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_progressions", (string)null);
                });

            modelBuilder.Entity("CannedNet.PlayerSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "key");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "playerId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Key")
                        .IsUnique();

                    b.ToTable("player_settings", (string)null);
                });

            modelBuilder.Entity("CannedNet.PromoExternalContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tooltip");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "url");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("promo_external_contents", (string)null);
                });

            modelBuilder.Entity("CannedNet.PromoImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "sortOrder");

                    b.Property<string>("Tooltip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tooltip");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("promo_images", (string)null);
                });

            modelBuilder.Entity("CannedNet.Room", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Accessibility")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accessibility");

                    b.Property<bool>("CloningAllowed")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "cloningAllowed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<int>("CreatorAccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "creatorAccountId");

                    b.Property<string>("CustomWarning")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "customWarning");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<bool>("DisableMicAutoMute")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "disableMicAutoMute");

                    b.Property<bool>("DisableRoomComments")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "disableRoomComments");

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "encryptVoiceChat");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "imageName");

                    b.Property<bool>("IsDorm")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isDorm");

                    b.Property<bool>("IsRRO")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isRRO");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "minLevel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomId");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<bool>("SupportsJuniors")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsJuniors");

                    b.Property<bool>("SupportsLevelVoting")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsLevelVoting");

                    b.Property<bool>("SupportsMobile")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsMobile");

                    b.Property<bool>("SupportsQuest2")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsQuest2");

                    b.Property<bool>("SupportsScreens")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsScreens");

                    b.Property<bool>("SupportsTeleportVR")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsTeleportVR");

                    b.Property<bool>("SupportsVRLow")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsVRLow");

                    b.Property<bool>("SupportsWalkVR")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "supportsWalkVR");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<int>("WarningMask")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "warningMask");

                    b.HasKey("Id");

                    b.HasIndex("CreatorAccountId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("CannedNet.RoomInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EncryptVoiceChat")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "EncryptVoiceChat");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("clubId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "clubId");

                    b.Property<string>("dataBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "dataBlob");

                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "eventId");

                    b.Property<bool>("isFull")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isFull");

                    b.Property<bool>("isInProgress")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isInProgress");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isPrivate");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("maxCapacity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "maxCapacity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("photonRegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "photonRegionId");

                    b.Property<string>("photonRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "photonRoomId");

                    b.Property<string>("roomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "roomCode");

                    b.Property<int>("roomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomId");

                    b.Property<int>("roomInstanceId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomInstanceId");

                    b.Property<int>("roomInstanceType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "roomInstanceType");

                    b.Property<int>("subRoomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "subRoomId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId", "roomId");

                    b.ToTable("room_instances", (string)null);
                });

            modelBuilder.Entity("CannedNet.RoomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accountId");

                    b.Property<int>("InvitedRole")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "invitedRole");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("room_roles", (string)null);
                });

            modelBuilder.Entity("CannedNet.SavedOutfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaceFeatures")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "FaceFeatures");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "HairColor");

                    b.Property<string>("OutfitSelections")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "OutfitSelections");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewImageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "PreviewImageName");

                    b.Property<string>("SkinColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "SkinColor");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Slot");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId")
                        .IsUnique();

                    b.ToTable("saved_outfits", (string)null);
                });

            modelBuilder.Entity("CannedNet.SubRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Accessibility")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "accessibility");

                    b.Property<string>("DataBlob")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "dataBlob");

                    b.Property<DateTime>("DataSavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "dataSavedAt");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isSandbox");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "maxPlayers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SubRoomId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "subRoomId");

                    b.Property<string>("UnitySceneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "unitySceneId");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("sub_rooms", (string)null);
                });

            modelBuilder.Entity("CannedNet.TokenBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Balance");

                    b.Property<int>("BalanceType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "BalanceType");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "CurrencyType");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "Platform");

                    b.HasKey("Id");

                    b.ToTable("token_balances", (string)null);
                });

            modelBuilder.Entity("CannedNet.Models.GiftDrop", b =>
                {
                    b.HasOne("CannedNet.Models.StorefrontItem", "StorefrontItem")
                        .WithMany("GiftDrops")
                        .HasForeignKey("StorefrontItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorefrontItem");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.HasOne("CannedNet.Models.Storefront", "Storefront")
                        .WithMany("Items")
                        .HasForeignKey("StorefrontId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storefront");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontPrice", b =>
                {
                    b.HasOne("CannedNet.Models.StorefrontItem", "StorefrontItem")
                        .WithMany("Prices")
                        .HasForeignKey("StorefrontItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorefrontItem");
                });

            modelBuilder.Entity("CannedNet.Models.Storefront", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CannedNet.Models.StorefrontItem", b =>
                {
                    b.Navigation("GiftDrops");

                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
