// <auto-generated />
using System;
using System.Collections.Generic;
using CannedNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CannedNet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405030000_AddFriendlyNameToReceivedGifts")]
    partial class AddFriendlyNameToReceivedGifts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ... (include the full model configuration like the previous migration)
            // For brevity, including just the ReceivedGift entity configuration

            modelBuilder.Entity("CannedNet.Models.ReceivedGift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemDesc");

                    b.Property<int>("AvatarItemType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "avatarItemType");

                    b.Property<int>("BalanceType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "balanceType");

                    b.Property<string>("ConsumableItemDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "consumableItemDesc");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "consumedAt");

                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "currency");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "currencyType");

                    b.Property<string>("EquipmentModificationGuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "equipmentModificationGuid");

                    b.Property<string>("EquipmentPrefabName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "equipmentPrefabName");

                    b.Property<int?>("FromPlayerId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "fromPlayerId");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "friendlyName");

                    b.Property<int>("GiftContext")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "giftContext");

                    b.Property<int>("GiftRarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "giftRarity");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isConsumed");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<int>("Platform")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platform");

                    b.Property<int>("PlatformsToSpawnOn")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "platformsToSpawnOn");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "receivedAt");

                    b.Property<int>("ReceiverAccountId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "receiverAccountId");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "xp");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverAccountId");

                    b.HasIndex("ReceiverAccountId", "IsConsumed");

                    b.ToTable("received_gifts", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}

